# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2404:2024.05.1
    resource_class: arm.medium
    steps:
      - checkout
      - run: bash setup_env.sh
      - run: bash build_mesa.sh
      - run: bash box86.sh
      - store_artifacts:
          path: ~/upload


workflows:
  my-workflow:
    jobs:
      - build
