# 使用Ubuntu arm64基础镜像
FROM arm64v8/ubuntu:24.04 As dev-image
WORKDIR /root

# 复制必要的文件到工作目录
COPY mesa mesa
COPY turnip-patches turnip-patches
COPY files files
COPY build_mesa.sh build_mesa.sh
COPY setup_env.sh setup_env.sh

# 配置环境并构建mesa
RUN bash setup_env.sh \
&& bash build_mesa.sh

# 构建后的文件保存在 /root/upload/ 目录下
