FROM arm64v8/ubuntu:24.04 As dev-image
WORKDIR /root
# 为了能apt build-dep需要添加deb-src。不确定security添加了src会不会有问题，但也不知道怎么排除。
RUN sed -i 's/Types: deb/Types:deb deb-src/g' /etc/apt/sources.list.d/ubuntu.sources \
&& dpkg --add-architecture armhf \
&& apt update \
&& apt upgrade -y \
&& apt build-dep -y mesa \
&& apt remove -y llvm-17 llvm-17-dev llvm-17-tools \
&& apt autoremove -y \
&& apt install -y libclang-18-dev libclang-common-18-dev libclang-cpp18-dev libclc-18 libclc-18-dev libllvmspirvlib-18-dev llvm-spirv-18 libpolly-18-dev llvm-18* \
&& apt install -y libssl-dev liblz4-dev liburing2 \
&& apt autoremove -y \
&& apt autoclean -y