name: 构建box86

on:
  schedule:
    - cron: '0 18 * * *'
  push:
  workflow_dispatch:

jobs:
  build-box86-aarch64:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
        
    - name: 克隆仓库
      uses: actions/checkout@v4
      
    - name: 下载交叉编译环境
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      continue-on-error: true
      with:
        workflow: create_bootstraps.yml
        workflow_conclusion: success
        path: /opt
        
    - name: 构建box86
      run: |
        sudo apt update
        sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf qemu-user-binfmt
        sudo tar -C /opt -xpf /opt/arm64_libs/arm64_libs.tar.xz
        chmod +x ./box86_cross.sh
        ./box86_cross.sh
        
    - name: 上传artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: box86-deb
        path: |
          /tmp/upload/*box86*.deb
        
    - name: 上传artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: box64-deb
        path: |
          /tmp/upload/*box64*.deb
          
    - name: 上传artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: all-tgz
        path: |
          /tmp/upload/*gz